title: "Roberto dos Reis, PhD" # your name (or website title) here
logo: "images/Roberto_Picture_for_Bio.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
Data scientist with strong physics and math background and 10+ yrs of experience using image processing/data analysis to solve complex materials problems.  
<br><br>
<a href="https://www.linkedin.com/in/robertodosreis/"> View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
